language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-26
    - extra-android-m2repository
    
before_install:
 - chmod +x gradlew

script:
  - ./gradlew build

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
